name: Benchmark

on:
  push:
    branches:
      - master

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [nightly]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Setup Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run benchmark
      run: cargo +nightly bench | tee output.txt
    - name: Fetch gh-pages for avoiding conflict
      run: git fetch 'https://dalance:${{ secrets.GITHUB_TOKEN }}@github.com/dalance/sv-parser.git' gh-pages:gh-pages
    - name: Store benchmark result
      uses: rhysd/github-action-benchmark@v1
      with:
        name: Rust Benchmark
        tool: 'cargo'
        output-file-path: output.txt
    - name: Push benchmark result
      run: git push 'https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/dalance/sv-parser.git' gh-pages:gh-pages
